### ISSUE TITLE
Gantry tilt pushing image out of field of view

### ISSUE THREAD

**Issue by muschellij2** [neurolabusc/dcm2niix#10]
The gantry tilt correction works very well, but the tilt correction can push areas of the image/brain "outside" the image or field of view.  For example, see below.  

Can't release data right now, but it may be possible to pad the image or recenter it?  I think you'd want to do something that's not based on intensity values as if you had 2 DICOMS from same scan, would want the same padding.

![image003](https://cloud.githubusercontent.com/assets/1075118/12833638/1e307bf6-cb5f-11e5-8e98-91fc79feda9c.png)
![image002](https://cloud.githubusercontent.com/assets/1075118/12833639/1e420682-cb5f-11e5-941e-95de287f6fe6.png)
![image001](https://cloud.githubusercontent.com/assets/1075118/12833640/1e4a1d86-cb5f-11e5-8dda-6ba267dec1a4.png)
![image000](https://cloud.githubusercontent.com/assets/1075118/12833641/1e4d4a2e-cb5f-11e5-9231-132b5acb1607.png)

**Comment by neurolabusc** [comment]
Yup no easy solution as the padding values could screw up normalization


Sent from my iPad

On Feb 4, 2016, at 6:49 PM, "John Muschelli" <notifications@github.com<mailto:notifications@github.com>> wrote:


The gantry tilt correction works very well, but the tilt correction can push areas of the image/brain "outside" the image or field of view. For example, see below.

Can't release data right now, but it may be possible to pad the image or recenter it? I think you'd want to do something that's not based on intensity values as if you had 2 DICOMS from same scan, would want the same padding.

[image003]<https://cloud.githubusercontent.com/assets/1075118/12833638/1e307bf6-cb5f-11e5-8e98-91fc79feda9c.png>
[image002]<https://cloud.githubusercontent.com/assets/1075118/12833639/1e420682-cb5f-11e5-941e-95de287f6fe6.png>
[image001]<https://cloud.githubusercontent.com/assets/1075118/12833640/1e4a1d86-cb5f-11e5-8dda-6ba267dec1a4.png>
[image000]<https://cloud.githubusercontent.com/assets/1075118/12833641/1e4d4a2e-cb5f-11e5-9231-132b5acb1607.png>

**Comment by neurolabusc** [comment]
John-
  Can you test out the latest build. It expands the image in the direction of the tilt, so no voxels are cropped. Empty voxels are filled with the darkest value in the observed data. I think this will be fine, though for normalization it might be worth using an implicit or explicit brain mask. There is also some translation of the image origin that I do not compensate for, but since this is normally dealt with by coregistration and normalization I do not think this is a problem.

![tilt](https://cloud.githubusercontent.com/assets/8930807/14227099/d0c7011e-f8c2-11e5-9ea2-8ce6ff235175.jpg)

**Comment by muschellij2** [comment]
I've received the following error:
```{bash}
Chris Rorden's dcm2niiX version 22Mar2016 (64-bit)
Version 22Mar2016 (64-bit)
Found 36 DICOM image(s)
 Warning: note these images have gantry tilt of -9 degrees (manufacturer ID = 1)
Convert 36 DICOM as ./_01_HEAD_20061216050422_2 (512x512x36x1)
compress: "/usr/local/bin/pigz" -n -f "./_01_HEAD_20061216050422_2.nii"
Gantry Tilt Correction is new: please validate conversions
dcm2niix(58210,0x7fff7b2f0300) malloc: *** error for object 0x7fff59c267d0: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
Tilt extends slice by 61 pixelsAbort trap: 6
```

**Comment by neurolabusc** [comment]
Can you send a sample dataset?

Sent from my iPhone

On Apr 3, 2016, at 9:39 PM, John Muschelli <notifications@github.com<mailto:notifications@github.com>> wrote:


I've received the following error:

Chris Rorden's dcm2niiX version 22Mar2016 (64-bit)
Version 22Mar2016 (64-bit)
Found 36 DICOM image(s)
 Warning: note these images have gantry tilt of -9 degrees (manufacturer ID = 1)
Convert 36 DICOM as ./_01_HEAD_20061216050422_2 (512x512x36x1)
compress: "/usr/local/bin/pigz" -n -f "./_01_HEAD_20061216050422_2.nii"
Gantry Tilt Correction is new: please validate conversions
dcm2niix(58210,0x7fff7b2f0300) malloc: *** error for object 0x7fff59c267d0: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
Tilt extends slice by 61 pixelsAbort trap: 6

**Comment by muschellij2** [comment]
Sent via email.

**Comment by neurolabusc** [comment]
Your issues are fixed with the latest release. Thanks for the samples.

**Comment by muschellij2** [comment]
Thanks!
