### ISSUE TITLE
enable config input

### ISSUE THREAD

**Issue by mgxd** [neurolabusc/dcm2niix#17]
Hi,
I'm working on adding dcm2niix to [nipype's](http://nipy.org/nipype/) interfaces, and was hoping there is way to implement a feature similar to dcm2nii's -b flag that allowed loading settings from specified config files.

**Comment by neurolabusc** [comment]
I think you would want to use the dcm2niibatch version, e.g. "dcm2niibatch run_configuration.yaml" as described here
  https://github.com/neurolabusc/dcm2niix

**Comment by mgxd** [comment]
Thanks for the info! 

A side note:
I was running into problems with the makefile not being able to find the path to yaml-cpp lib, so had to hack the paths directly. Perhaps adding a subtree of the yaml-cpp git repo to this one could make the process more user-friendly?

**Comment by benjaminirving** [comment]
@mgxd,

Yes. We need to look into making the dependencies of `dcm2niibatch` a bit more user friendly. Did you also have `pkg-config` installed? Did you install `yaml-cpp` through apt-get or brew, or manually? Perhaps, writing a `FindYamlCpp.cmake` file that also searches the local path is an option. Unfortunately, cmake doesn't come with a `FindYamlCpp.cmake` file already. 

When I added `dcm2niibatch`, I tried to make the footbprint as small as possible to not distract from the main binary `dcm2nii`

Ben

p.s We've just put this batch version together and it still needs a few tweaks so please let us know if you run into other issues.

**Comment by mgxd** [comment]
@benjaminirving, yes pkg-config was already installed - the only missing component was yaml-cpp, which I installed by git cloning the repo and then building it manually.

Does dcm2niibatch use the same dicom conversion method as dcm2niix? I assumed it did.

Thanks Ben, and I'll let you know if I encounter other issues

**Comment by benjaminirving** [comment]
@mgxd, yes, the methods for dicom processing are identical. The only thing different is some wrapper code to read the yaml file and pass the inputs.  But there could be some improvements in how we do that. 

pkg-config will probably only be able to find yaml-cpp if installed via a package manager like `apt-get` or `homebrew`. I'll look into this. 

Ben
