### ISSUE TITLE
BIDSification sensitive to top-level JSONs?

### ISSUE THREAD

**Issue by jpellman** [neurolabusc/dcm2niix#19]
Pardon me if this question is answered elsewhere, but is the "isCreateBIDS" option in the configuration YAML sensitive to whether or not there are JSONS in the top-level directory of a BIDS dataset directory that should be inherited by NifTIs?  I.e., is it able to open up JSONS at the top-level directory, compare the parameters in those JSONS to the JSON files that would potentially be written out at the participant level, and then not write out JSONS at the participant level if the top-level and participant-level JSONs are the same?

**Comment by benjaminirving** [comment]
@jpellman, the YAML and batch wrapper was created to replicate the functionality of the standard `dcm2nii` script for multiple sets of images. 

`isCreateBIDS` should correspond to running `dcm2nii -b` etc for a single folder.  I wrote the wrapper but don't use this option, so perhaps @neurolabusc can answer the specifics of `dcm2nii -b`

**Comment by chrisfilo** [comment]
dcm2niix BIDS support works on a per file basis - it is not aware of
the folder structure. So the isCreateBIDS or -b will create BIDS compatible
.json files next to each converted .nii.gz. The functionality you are
describing  would be neat, but might be outside of the scope of dcm2niix.
