### ISSUE TITLE
dicom splitting during conversion

### ISSUE THREAD

**Issue by mgxd** [neurolabusc/dcm2niix#20]
I'm curious to how dicoms are split up during conversion.
[Here](http://pastebin.com/DGp7TvFe) is an output of a conversion I ran.

Is there a difference between outputs such as:
`Convert 70 DICOM as ./S032_DIFFUSION_HighRes_AP (128x128x64x70)`
`Convert 64 DICOM as ./S032_DIFFUSION_HighRes_APa (128x128x64x1)`
where an `a` is just added to the filename, compared to:
`Convert 64 DICOM as ./S032_field_mapping_diffusion (128x128x64x1)`
`Convert 64 DICOM as ./S032_field_mapping_diffusion_c0_2 (128x128x64x1)`
`Convert 64 DICOM as ./S032_field_mapping_diffusion_c0_2a (128x128x64x1)`
where `_c0_2` is added, and then `a` is added as well?

**Comment by neurolabusc** [comment]
Mattias-
  Yes, a field map that is based on multiple echoes should generate separate images. Likewise, a image where magnitude and phase data are stored should generate two images. In your case, your field map is acquired using two echoes and results in two magnitude images and one phase image. The conversion is correct, but the naming will lot better if you download and build the latest version as I have worked out how to detect phase maps from Siemens systems. With the latest software your images will be named
  S032_field_mapping_diffusion
  S032_field_mapping_diffusion_e2
  S032_field_mapping_diffusion_e2_ph
This designates that the first echo yielded one magnitude image, and the second echo (_e2) yielded both a magnitude image as well as a phase (_ph) image.
