### ISSUE TITLE
dcm2niix -x auto crop function

### ISSUE THREAD

**Issue by yinkaiming1987** [neurolabusc/dcm2niix#21]
Dear guys,

As the old dcm2nii can do the auto crop (i.e. dcm2nii -x <input>) on the brain images to have a proper FOV, which is especially useful when the image contains a big part of the neck tissue. Could I ask if the new dcm2niix has a similar function? The flag "-x" seems not working any more.

Thanks,
Kaiming

**Comment by neurolabusc** [comment]
Kaiming,
  As requested, I have added the -x option to crop 3D acquisitions with short echo times (e.g. T1 scans). Please test out the latest 5May2016 release. The algorithm is inspired by my older dcm2nii, but I think it is a bit more effective for T1 scans where an individual has a lot of bright neck fat.

I do think cropping can help normalization, as bright neck signals can throw off the initial stages of spatial registration. However, the methods of dcm2nii and dcm2niix are pretty simplistic. SPM users may want to take a look at my script which uses SPM's coregistration function to estimate the origin and then losslessly sets a reasonable bounding box:
https://github.com/neurolabusc/spmScripts/blob/master/nii_setOrigin12.m
