### ISSUE TITLE
output directory switch not working

### ISSUE THREAD

**Issue by diego0020** [neurolabusc/dcm2niix#23]
Hi
I am noticing that the output directory switch `-o` is not working, and output is always written to the input directory.
I think it has to do with the
```c
strcpy(opts.outdir,opts.indir);
```
line at the end of `main_console.cpp`

**Comment by neurolabusc** [comment]
Well spotted, fixed in new (20-May-2016) version. An unintended consequence of the changes added to the 30-Apr-2016 version described here
  https://github.com/nipy/nipype/issues/1389#issuecomment-216122784
