### ISSUE TITLE
conversion of single DICOM images

### ISSUE THREAD

**Issue by efunn** [neurolabusc/dcm2niix#3]
I currently use the original **dcm2nii** in a real-time fMRI workflow using FSL tools. Our Siemens scanner dumps DICOMs into `some_folder`, so I set a watch on `some_folder` and call `dcm2nii -v n some_folder/image.dcm` for each image that appears, which gives me a NIFTI that I can use FSL on.

I'm interested in using **dcm2niix** because of the speed increase on Siemens DICOMs. However, single image processing does not appear to be available any more.

My current solution is:
- detect `path/to/unique_image.dcm` appearing
- create `path/to/unique_image_folder` 
- copy `path/to/unique_image.dcm` to `path/to/unique_image_folder`
- call `dcm2niix -o path/to -f unique_image path/to/unique_image_folder`
- remove `path/to/unique_image_folder`
- resulting in `path/to/unique_image.nii` and no extra folders in `path/to/`

I'm wondering if the option to convert single images by  calling `dcm2nii --some-argument path/to/single/image.dcm` still exists in **dcm2niix** but I'm missing how to pass the argument. If not, is there any future plan to re-implement this feature?

**Comment by neurolabusc** [comment]
Hello-
  I have added this feature to the 27Aug2015 release. You can either compile your own copy or use a precompiled version (in the 'osx_binary' and 'linux_binary' folders. To convert single files you would use the '-s Y' switch, so "./dcm2niix -s Y /test/myDICOM.dcm". While this software might be a touch faster than other tools for single files, the real performance benefits are seen when converting large numbers of files. With a single file disk access is probably the limiting factor. If speed is important avoid saving data in a compressed format (.nii.gz) as that has a big overhead.

**Comment by efunn** [comment]
Tested the precompiled Linux version and the '-s Y' switch works as expected. Thank you!
