### ISSUE TITLE
'fieldStrength' field is never set

### ISSUE THREAD

**Issue by chrisfilo** [neurolabusc/dcm2niix#30]
I can see the fieldStrength is being defined here: https://github.com/neurolabusc/dcm2niix/blob/5bb057e8d6903d08a5ad7bb21d627d5de8f8f110/console/nii_dicom.h#L57

read here: https://github.com/neurolabusc/dcm2niix/blob/5bb057e8d6903d08a5ad7bb21d627d5de8f8f110/console/nii_dicom_batch.cpp#L336

but it is never set. Thus it's always 0 for all input files.

**Comment by neurolabusc** [comment]
Can you test the latest code to - this should set fieldStrength if tag 0018,0087 is present (a required tag for MRI-based DICOM images).
