### ISSUE TITLE
cmake problem finding yaml-cpp on Mac OS. 

### ISSUE THREAD

**Issue by hfxcarl** [neurolabusc/dcm2niix#34]
In trying to compile dcm2niix on Mac OS 10.11, I was repeated stymied with this error
 "-- Checking for module 'yams-cpp'
 --   No package 'yaml-cpp' found"

I found a fix to patch the CMakeLists.txt file from this website (https://github.com/dapicester/image-search/blob/master/cmake/Modules/FindYamlCpp.cmake).

I'm just learning to use Git. Would someone else mind updating the dcm2niix-master CMakeLists.txt file?
Thanks,
Carl

**Comment by benjaminirving** [comment]
Hi Carl, 

yaml is only required by Cmake if you're trying to compile the dcm2niibatch version.

For the batch version, I will check this on OSx in the next couple of days and get back to you. 

Ben

**Comment by benjaminirving** [comment]
Hi Carl, 
The easiest way to install and manage package dependencies in OSx is to use homebrew (http://brew.sh/)

I would suggest that you install homebrew and then install the package dependencies i.e.

```bash
brew install yaml-cpp pkg-config cmake
```
After this then dcm2niix will find all the dependencies. It works on my system but would you be willing to also test this? I'll then update the documentation.

**Comment by hfxcarl** [comment]
Hi Ben,

No problem, I'll test a home-brew install of yaml-cpp on Monday when I'm back in the lab with access to a Mac and get back to you.

I had independently downloaded, compiled on terminal with Xcode's clang compiler, and installed yaml-cpp (and its dependency boost) into /usr/local/. If you would like, I could also send you instructions for doing this.

Cheers,
Carl

On Jul 1, 2016, at 07:03, Benjamin Irving <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Carl,
The easiest way to install and manage package dependencies in OSx is to use homebrew (http://brew.sh/)

I would suggest that you install homebrew and then install the package dependencies i.e.

brew install yaml-cpp pkg-config cmake

After this then dcm2niix will find all the dependencies. It works on my system but would you be willing to also test this? I'll then update the documentation.

-

**Comment by neurolabusc** [comment]
Carl,

 I have updated the "Build" instructions on the main github page, adding Ben's suggestion that you can run "brew install yaml-cpp pig-config cmake" on MacOSX. I also added the comment that unless you need the batch version you can simply call "make" instead co "make" and get a compile with the minimum of required dependencies. 

Once you test this, can you let us know and I will close this issue.
