### ISSUE TITLE
dcm2niibatch: Manually linking yaml-cpp libs for CentOS build

### ISSUE THREAD

**Issue by dangom** [neurolabusc/dcm2niix#38]
Dear neurolabusc,

I lack the necessary permissions to `sudo apt-get install libyaml-cpp-dev libyaml-cpp0.5` on the server I'm using. Therefore I'd like to build yaml-cpp somewhere on my home directory (from sources [here](https://github.com/jbeder/yaml-cpp)) and then manually tell CMake where to find the libraries.

After googling around I tried adding these three lines to CMakeLists.txt, but that didn't work.

`set(CMAKE_MODULE_PATH "/home/mrphys/dangom/clones/yaml-cpp/build;${CMAKE_MODULE_PATH}")
set(CMAKE_LIBRARY_PATH "/home/mrphys/dangom/clones/yaml-cpp/build;${CMAKE_LIBRARY_PATH}")
set(CMAKE_INCLUDE_PATH "/home/mrphys/dangom/clones/yaml-cpp/build;${CMAKE_INCLUDE_PATH}")
`

Cmake complains that it can't find the yaml-cpp package.

> Creating batch version
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.27.1") 
-- checking for module 'yaml-cpp'
--   package 'yaml-cpp' not found

Would you have any suggestions on how I can solve this issue? 

Thanks!

**Comment by benjaminirving** [comment]
@dangom, 
This should be manageable with the cmake file. I'll look into modifying it in the next couple of days.

**Comment by benjaminirving** [comment]
I've created the following branch
https://github.com/neurolabusc/dcm2niix/tree/test_cmake_yaml
This version should be able to work with a locally downloaded version of yaml-cpp in the source folder.
- Download yaml-cpp into the source folder
- Make sure the folder is called yaml-cpp

cmake should be able to find it but you would still need to have all of yaml-cpp dependencies. Would you mind testing this to see if it works for you?

**Comment by dangom** [comment]
Hi Benjamin,

Thanks for the quick answers.
The build is working just fine now.
