### ISSUE TITLE
when will 15 aug version be posted on nitrc

### ISSUE THREAD

**Issue by satra** [neurolabusc/dcm2niix#41]

**Comment by neurolabusc** [comment]
I want to address 3 issues before an official release, all related to the reorienting of DTI vectors:

1.) Paul Morgan has provided a validation dataset for GE coronal and transverse acquisitions
https://www.nitrc.org/plugins/mwiki/index.php/dcm2nii:MainPage#Diffusion_Tensor_Imaging

2.) Hans Johnson has demonstrated that Siemens scanners can generate DTI scans where the first "protocolSliceNumber" is not 1. E.G. where the slices are not stored in a spatially ascending order. This causes my software to generate warnings, and while his samples process correctly with FSL, they cause problems with slicer.

3.) Acquire Siemens validation datasets with where the Mosaic has a Negative Determinant to ensure we handle the bvec reorientation correctly.

Xiangrui Li's recent releases of dicm2nii address (1) and has a new algorithm that appears much more elegant for (3). The latest Github code includes a preliminary port of his algorithm, but employing it would require extensive validation testing for unintended consequences (e.g. Xiangrui's code does not deal with CT scans with unequal slice spacing).

**Comment by satra** [comment]
@neurolabusc - thank you for the update.

**Comment by neurolabusc** [comment]
Satra-
  Can you test out the latest version (26Aug2016). I tried to validate all the datasets available at http://www.nitrc.org/plugins/mwiki/index.php/dcm2nii:MainPage#Diffusion_Tensor_Imaging (and added some new validation datasets we acquired on the Prisma). The only outstanding issue #42, which I can replicate myself with the latest version. Unless someone reports any issues, this should be ready for release.

**Comment by neurolabusc** [comment]
I have generated a new release
  https://github.com/neurolabusc/dcm2niix/releases/tag/20160921
This is currently labeled as a pre-release, but unless I hear about any issues, this will be released on NITRC in a couple days.

**Comment by neurolabusc** [comment]
New stable release (30-Sept-2016).
