### ISSUE TITLE
random (? ;-)) gl* and some other header values in the generated nii.gz

### ISSUE THREAD

**Issue by yarikoptic** [neurolabusc/dcm2niix#45]
Sorry for a big long report, which evolved while I was digging through the issue:

rerunning the same dcm2niix (0.20160606.1+git22-gf6471c0-1~nd90+1) call results in nifti files with differing headers: e.g.
```shell
$> nifti_tool -diff_hdr -infiles out/PHANTOM1_3.nii.gz out1/PHANTOM1_3.nii.gz 
  name                offset  nvals  values
  ------------------- ------  -----  ------
  glmax                140      1    32643
  glmax                140      1    32635
  glmin                144      1    -425050208
  glmin                144      1    -1197384832
```
so I have built bleeding edge 20160606-50-g236b267 and difference on this particular set of files disappeared across few reruns BUT reappeared while converting other files and this time only in glmax (so I guess glmin issue got somehow addressed) and session_error:

```
$> niidiff ../outputs-test-reran{9,10}/PHANTOM1_3/run003-0.nii.gz                                               
NIfTI header diff: ../outputs-test-reran9/PHANTOM1_3/run003-0.nii.gz -> ../outputs-test-reran10/PHANTOM1_3/run003-0.nii.gz
  name                offset  nvals  values
  ------------------- ------  -----  ------
  session_error         36      1    32767
  session_error         36      1    32765
....
$> niidiff ../outputs-test-reran{8,10}/PHANTOM1_3/run002-0.nii.gz 
NIfTI header diff: ../outputs-test-reran8/PHANTOM1_3/run002-0.nii.gz -> ../outputs-test-reran10/PHANTOM1_3/run002-0.nii.gz
  name                offset  nvals  values
  ------------------- ------  -----  ------
  glmax                140      1    32766
  glmax                140      1    32765
```

So I have cooked up a tarball with data/script/output to reproduce:  http://www.onerussian.com/tmp/dcm2niix-bug.20160918.tgz

```shell
$> ./outputs-test-reran10.sh 
Chris Rorden's dcm2niiX version 28Aug2016 (64-bit Linux)
Found 5 DICOM image(s)
slices not stacked: orientation varies (localizer?) [-0.050626 0.971613 -0.231097 -0.0485989 -0.233516 -0.971138] != [-0.731964 0.669963 -0.124007 -0.056041 -0.240586 -0.969009] ('-m y' to force stacking)
Convert 2 DICOM as out/PHANTOM1_3 (162x162x2x1)
slices not stacked: orientation varies (localizer?) [-0.731964 0.669963 -0.124007 -0.056041 -0.240586 -0.969009] != [-0.0393658 0.998954 -0.0232823 -0.0580964 -0.0255492 -0.997984] ('-m y' to force stacking)
Convert 1 DICOM as out/PHANTOM1_3a (162x162x1x1)
WARNING: check that 2D images are not mirrored.
slices not stacked: orientation varies (localizer?) [-0.0393658 0.998954 -0.0232823 -0.0580964 -0.0255492 -0.997984] != [0.633816 0.741325 -0.220712 -0.056041 -0.240586 -0.969009] ('-m y' to force stacking)
Convert 1 DICOM as out/PHANTOM1_3b (162x162x1x1)
WARNING: check that 2D images are not mirrored.
slices not stacked: orientation varies (localizer?) [0.633816 0.741325 -0.220712 -0.056041 -0.240586 -0.969009] != [-0.050626 0.971613 -0.231097 -0.0485989 -0.233516 -0.971138] ('-m y' to force stacking)
Convert 1 DICOM as out/PHANTOM1_3c (162x162x1x1)
WARNING: check that 2D images are not mirrored.
Conversion required 0.026548 seconds.

$> mv out out1

$> ./outputs-test-reran10.sh; md5sum out{,1}/PHANTOM1_3.nii.gz
Chris Rorden's dcm2niiX version 28Aug2016 (64-bit Linux)
Found 5 DICOM image(s)
slices not stacked: orientation varies (localizer?) [-0.050626 0.971613 -0.231097 -0.0485989 -0.233516 -0.971138] != [-0.731964 0.669963 -0.124007 -0.056041 -0.240586 -0.969009] ('-m y' to force stacking)
Convert 2 DICOM as out/PHANTOM1_3 (162x162x2x1)
slices not stacked: orientation varies (localizer?) [-0.731964 0.669963 -0.124007 -0.056041 -0.240586 -0.969009] != [-0.0393658 0.998954 -0.0232823 -0.0580964 -0.0255492 -0.997984] ('-m y' to force stacking)
Convert 1 DICOM as out/PHANTOM1_3a (162x162x1x1)
WARNING: check that 2D images are not mirrored.
slices not stacked: orientation varies (localizer?) [-0.0393658 0.998954 -0.0232823 -0.0580964 -0.0255492 -0.997984] != [0.633816 0.741325 -0.220712 -0.056041 -0.240586 -0.969009] ('-m y' to force stacking)
Convert 1 DICOM as out/PHANTOM1_3b (162x162x1x1)
WARNING: check that 2D images are not mirrored.
slices not stacked: orientation varies (localizer?) [0.633816 0.741325 -0.220712 -0.056041 -0.240586 -0.969009] != [-0.050626 0.971613 -0.231097 -0.0485989 -0.233516 -0.971138] ('-m y' to force stacking)
Convert 1 DICOM as out/PHANTOM1_3c (162x162x1x1)
WARNING: check that 2D images are not mirrored.
Conversion required 0.023688 seconds.
1e3816b92567159bbc5cd900bc5ce068  out/PHANTOM1_3.nii.gz
697b0b296b84803d51c35035591bb5bc  out1/PHANTOM1_3.nii.gz

$> niidiff out{,1}/PHANTOM1_3.nii.gz                          
NIfTI header diff: out/PHANTOM1_3.nii.gz -> out1/PHANTOM1_3.nii.gz
  name                offset  nvals  values
  ------------------- ------  -----  ------
  glmax                140      1    32765
  glmax                140      1    32767
```

even if input is problematic, output imho should be deterministic ;)
If I run that call through valgrind, it screams at me with lots of uses or jumps based on uninitialized values... worrisome:  http://www.onerussian.com/tmp/dcm2niix-20160918-valgrind.txt

related: I wondered -- is there any kind of automated testing established for dcm2niix?

**Comment by neurolabusc** [comment]
The items you note are all unused portions of the NIfTI header (included to make the header align to the older Analyze format). However, I do think we should initialize arrays to zero: first of all to ensure deterministic outcome which makes identifying real errors easier. Secondly, since C does not automatically initialize arrays you may get private data that was previously in the buffer. Please check todays release - I think this comprehensively addresses this issue. With regards to the valgrind output, it looks like all the reports refer to the use of miniz to compress data. Given the popularity of that code, I do not think the initialized values there have any consequence, but it you want to research it and suggest a patch (probably directly to the miniz github project) it would be useful, if nothing else to make cleaner debugging. I would be also happy to incorporate a formal test battery. I include sample datasets from all the major vendors here
  https://www.nitrc.org/plugins/mwiki/index.php/dcm2nii:MainPage#Diffusion_Tensor_Imaging
alternatively, you could use the Rosetta Bit dataset.

**Comment by yarikoptic** [comment]
awesome -- thank you!  I will build updated package for NeuroDebian asap

"Given the popularity of that code, I do not think the initialized values there have any consequence" -- most probably you are right BUT we have had precedents, so I wouldn't swear by it ;)  (note though that there was a new bugfix release 1.16 since the one you bundle 1.15: https://code.google.com/archive/p/miniz/) so may be update for it?

Thanks for the pointers to sample DICOMs but do you have some automated way to use those? i.e. to verify that converted files conform to the expected values (in the header and data).  Would be of great help while building across distros/architectures and possibly would help to identify some gotchas

**Comment by neurolabusc** [comment]
1.) Where is Miniz 1.16 hosted? The google page https://code.google.com/archive/p/miniz/ lists that as beta ("v1.16 BETA - Oct 19, 2013") and the Github page still lists 1.15 as the master branch (https://github.com/richgel999/miniz).

2.) I think a simple shell script could be created that would download a set of DICOMs as well as verified NIfTI conversions, run the conversions and then check whether the output is different. Of course, one has to make assumptions about what the right answer is, for example dicm2nii likes to rotate DTI image data so that the SForm is aligned with the identity matrix while dcm2niix keeps the same alignment as the raw DICOM data. Both are lossless correct answers but will appear very different to a simple byte difference checked. I am just ramping up the neuroimaging core for a NIH p50, and this means I have precious little time for other work. Therefore, I would be happy if someone wants to pursue this but in the medium term I am spread to thin to commit to new endeavors.

**Comment by yarikoptic** [comment]
On Mon, 19 Sep 2016, Chris Rorden wrote:

>    1.) Where is Miniz 1.16 hosted? The google page
>    https://code.google.com/archive/p/miniz/ lists that as beta ("v1.16 BETA -
>    Oct 19, 2013") and the Github page still lists 1.15 as the master branch
>    (https://github.com/richgel999/miniz).

yeap -- lists as beta -- I guess never released... feel free to
disregard my PR if you think it is more pain than gain

>    2.) I think a simple shell script could be created that would download a
>    set of DICOMs as well as verified NIfTI conversions, run the conversions
>    and then check whether the output is different. Of course, one has to make
>    assumptions about what the right answer is, for example dicm2nii likes to
>    rotate DTI image data so that the SForm is aligned with the identity
>    matrix while dcm2niix keeps the same alignment as the raw DICOM data. Both
>    are lossless correct answers but will appear very different to a simple
>    byte difference checked. I am just ramping up the neuroimaging core for a
>    NIH p50, and this means I have precious little time for other work.
>    Therefore, I would be happy if someone wants to pursue this but in the
>    medium term I am spread to thin to commit to new endeavors.

yeap -- time permitting we will look to help out with such a
script/testing. may be using testkraut ;) (right @satra and @mih?) But I
more wondered on how **YOU** test it to do the right thing - i.e.  if
there was anything automated so we don't start with mere regression
tests?

-- 
Yaroslav O. Halchenko
Center for Open Neuroscience     http://centerforopenneuroscience.org
Dartmouth College, 419 Moore Hall, Hinman Box 6207, Hanover, NH 03755
Phone: +1 (603) 646-9834                       Fax: +1 (603) 646-1419
WWW:   http://www.linkedin.com/in/yarik

**Comment by yarikoptic** [comment]
"batch convert the whole folder" and just see that it crashes or not (smoke test) or actually checking any of the outputs for correct values?  i.e. we could possibly define some target values to expect converted niftis to have for some header fields etc

**Comment by yarikoptic** [comment]
FWIW, this particular issue was resolved, thus closing.
BTW -- this snapshot build was uploaded to NeuroDebian

**Comment by yarikoptic** [comment]
BTW @neurolabusc - I think I have reported already but forgot where -- some tarballs from the nitrc wiki page you referenced are no longer available, e.g. http://www.mccauslandcenter.sc.edu/crnl/sw/dcm2niix/sliceorder_Siemens_SC.zip

**Comment by neurolabusc** [comment]
I fixed most of those, but missed that one. Fixed now.

In terms of testing I do test that nothing crashes, but also inspect things that I think will change.

**Comment by yarikoptic** [comment]
if interested -- here is a git-annex/datalad "version" of that dataset (without fetching any of those previously failing... will need to recrawl):  http://datasets.datalad.org/?dir=/dicoms/dcm2niix-tests . So, someone could just do `datalad install -g ///dicoms/dcm2niix-tests` to fetch all those dicoms (from your hosting, your tarballs... ;) )
