### ISSUE TITLE
please use annotated (and/or signed) tags for releases

### ISSUE THREAD

**Issue by yarikoptic** [neurolabusc/dcm2niix#52]
to amuse users I guess, regular 'git tag' command without -m creates just a pointer, not a fully fledged "git tag".  It is recommended to use annotated (created by using -m) tags for releases so e.g. describe works nicely

```shell
$> git describe upstream/master
20160606-68-gf7b898b

$> git describe --tags upstream/master 
20160921-15-gf7b898b
```

**Comment by yarikoptic** [comment]
I see 3 "schemes" of tags now present

20160606
20160921
30-Sept-2016
v1.0.20160930

so which one would be the one for releases? The one with v prefix?

**Comment by neurolabusc** [comment]
I am personally agnostic on this, but I realize others have strong opinions
 https://github.com/neurolabusc/MRIcroGL/issues/1#issuecomment-156719640
For the recent release, I followed the suggestion by GitHub that you see when you create a release, e.g. 
  v1.0.20160930
We might as well keep this style in the future, e.g. the stable release from the 30-Sept-2016 code gets release v1.0.20160930

**Comment by yarikoptic** [comment]
On Fri, 07 Oct 2016, Chris Rorden wrote:

>    I am personally agnostic on this, but I realize others have strong
>    opinions
>    neurolabusc/MRIcroGL#1 (comment)
>    For the recent release, I followed the suggestion by GitHub that you see
>    when you create a release, e.g.
>    v1.0.20160930
>    We might as well keep this style in the future, e.g. the stable release
>    from the 30-Sept-2016 code gets release v1.0.20160930

I am agnostic too as long as they are consistent so could be sorted
automatically etc. (and annotated of cause ;) )
